# Generated by Django 5.1.3 on 2024-11-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classerpg',
            name='main_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributo_principal', to='myapp.atributorpg'),
        ),
        migrations.AlterField(
            model_name='classerpg',
            name='secundario_atributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributo_secundario', to='myapp.atributorpg'),
        ),
    ]
