# Generated by Django 5.1.3 on 2024-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_classerpg_main_atributo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classerpg',
            name='descricao',
            field=models.TextField(default='descrição pendente'),
            preserve_default=False,
        ),
    ]
