# Generated by Django 5.1.3 on 2024-11-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_classerpg_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterrpg',
            name='mana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracterrpg',
            name='vida',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracterrpg',
            name='vivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classerpg',
            name='mana',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.atributorpg')),
                ('caracter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caracterrpg')),
            ],
            options={
                'unique_together': {('caracter', 'atributo')},
            },
        ),
        migrations.AddField(
            model_name='caracterrpg',
            name='atributos',
            field=models.ManyToManyField(through='myapp.ValorAtributo', to='myapp.atributorpg'),
        ),
    ]
