# Generated by Django 5.1.3 on 2024-11-29 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_caracterhabilidade_characterhabilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrpg',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrpg',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='RaceRPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('bonus_valor', models.IntegerField(default=0)),
                ('bonus_atributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.atributorpg')),
            ],
        ),
    ]
