# Generated by Django 5.1.3 on 2024-11-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_characterrpg_exp_alter_characterrpg_level_racerpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrpg',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.racerpg'),
        ),
    ]
