# Generated by Django 5.1.3 on 2024-11-29 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_characterrpg_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('exp_needed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='characterrpg',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.levelrpg'),
        ),
    ]
