# Generated by Django 5.1.3 on 2024-11-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_levelrpg_alter_characterrpg_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classerpg',
            name='mana_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classerpg',
            name='vida_base',
            field=models.IntegerField(default=0),
        ),
    ]
