# Generated by Django 5.1.3 on 2024-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_classerpg_mana_base_classerpg_vida_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrpg',
            name='mana_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrpg',
            name='vida_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='acao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='mana_gasto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='acao_extra',
            field=models.IntegerField(default=0),
        ),
    ]
