# Generated by Django 5.1.3 on 2024-11-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_characterrpg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrpg',
            name='mana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='characterrpg',
            name='vida',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StatusPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=27)),
                ('caracter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.characterrpg')),
            ],
        ),
    ]
